version: "3"

networks:
  loki:
    driver: bridge
    name: loki_network

services:
  app:
    image: nginx:latest
    container_name: user_app
    ports:
      - "80:80"
    volumes:
      - ./app:/usr/share/nginx/html
    networks:
      - loki

  loki:
    image: grafana/loki:latest
    container_name: loki
    ports:
      - "3100:3100"
    volumes:
      - /root/promtailloki/loki:/etc/loki
    command: -config.file=/etc/loki/loki-config.yml
    networks:
      - loki

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus:/etc/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    networks:
      - loki

  promtail:
    image: grafana/promtail:latest
    container_name: promtail
    volumes:
      - /var/log:/var/log
      - /root/promtailloki/promtail:/etc/promtail
    command: -config.file=/etc/promtail/promtail-config.yml
    networks:
      - loki

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    networks:
      - loki
